# Generated by Django 4.2.5 on 2023-09-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_3',
        ),
    ]
